# Generated by Django 5.0 on 2024-02-01 07:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0003_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='products',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_offer', to='admin_products.category')),
            ],
        ),
    ]
