# Generated by Django 5.0 on 2024-01-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_banner', '0002_rename_usedcoupon_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='is_applyed',
            field=models.BooleanField(default=False),
        ),
    ]
