# Generated by Django 5.0 on 2024-01-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='referal_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
