# Generated by Django 5.0 on 2024-01-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0002_orderitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='price',
            field=models.FloatField(),
        ),
    ]
