# Generated by Django 5.0 on 2024-01-18 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0003_alter_orderitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('Cash_on_Delevery', 'Cash on Delevery'), ('Razorpay', 'Razorpay'), ('PayPal', 'PayPal'), ('Wallet', 'Wallet')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('razorpay_payment_id', models.CharField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_order.order')),
            ],
        ),
    ]
