# Generated by Django 5.0 on 2024-01-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0004_remove_order_delivery_date_remove_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
    ]
